<template><view class="page"><page-header title="账户余额"/><view class="card hero"><text class="label">可用余额</text><text class="amount">¥ {{amount}}</text><text class="hint">本地演示充值仅用于测试，不会产生真实支付</text></view><view class="card"><view class="title-row"><text class="title">充值测试</text><text class="muted">选择金额后确认</text></view><view class="amounts"><button v-for="v in amounts" :key="v" :class="['amount-btn',{active:selected===v}]" @click="selected=v">¥{{v}}</button></view><button class="primary" :disabled="loading" @click="recharge">{{loading?'处理中':'确认模拟充值'}}</button></view><view class="card"><view class="title-row"><text class="title">余额流水</text><text class="muted">{{ledger.length}} 条</text></view><view v-if="!ledger.length" class="empty">暂无余额流水</view><view v-for="row in ledger" :key="row.request_id" class="row"><view><text class="row-title">{{row.remark || '余额变动'}}</text><text class="row-time">{{row.create_time}}</text></view><text :class="['delta',Number(row.amount)>=0?'plus':'minus']">{{Number(row.amount)>=0?'+':''}}{{Number(row.amount).toFixed(2)}} 元</text></view></view></view></template>
<script setup>
import {ref} from 'vue';import {onShow} from '@dcloudio/uni-app';import pageHeader from '../../components/page-header/index.vue';import request from '../../components/js/request.js'
const amount=ref('0.00'),ledger=ref([]),selected=ref(10),loading=ref(false),amounts=[10,20,50,100]
function load(){request({url:'wallet/summary',success:r=>{if(r.data?.code===200)amount.value=Number(r.data.data?.amount||0).toFixed(2)}});request({url:'wallet/ledger',data:{page:1,pageSize:20},success:r=>{if(r.data?.code===200)ledger.value=r.data.data||[]}})}
function recharge(){if(loading.value)return;loading.value=true;const id='mini-'+Date.now()+'-'+Math.random().toString(36).slice(2);request({url:'wallet/recharge',method:'POST',data:{amount:selected.value,requestId:id},success:r=>{if(r.data?.code===200){uni.showToast({title:'充值成功',icon:'success'});load()}else uni.showToast({title:r.data?.msg||'充值失败',icon:'none'})},complete:()=>loading.value=false})}
onShow(()=>{if(uni.getStorageSync('token'))load()})
</script>
<style scoped>.page{min-height:100vh;background:#f3f7f5;padding-bottom:40rpx}.card{margin:22rpx 28rpx;background:#fff;border-radius:24rpx;padding:28rpx;box-sizing:border-box}.hero{background:linear-gradient(135deg,#008773,#1aa98c);color:#fff}.label{display:block;font-size:25rpx;opacity:.85}.amount{display:block;font-size:64rpx;font-weight:700;margin:18rpx 0}.hint{font-size:22rpx;opacity:.8}.title-row{display:flex;justify-content:space-between;align-items:center}.title{font-size:30rpx;font-weight:700}.muted,.row-time{font-size:22rpx;color:#8a9b92}.amounts{display:flex;gap:16rpx;margin:24rpx 0}.amount-btn{flex:1;background:#f3f7f5;color:#44675a;font-size:26rpx;padding:16rpx 0;border-radius:14rpx}.amount-btn::after{border:0}.amount-btn.active{background:#dff3ea;color:#008773;border:1rpx solid #6dc9ac}.primary{background:#008773;color:#fff;border-radius:14rpx}.primary::after{border:0}.row{display:flex;justify-content:space-between;align-items:center;padding:22rpx 0;border-bottom:1rpx solid #edf2ef}.row:last-child{border:0}.row-title{display:block;font-size:27rpx}.delta{font-size:28rpx;font-weight:700}.plus{color:#008773}.minus{color:#bd654f}.empty{text-align:center;color:#9aaba2;padding:45rpx 0;font-size:24rpx}</style>
