<template><view class="page"><page-header title="积分中心"/><view class="card hero"><text class="label">当前积分</text><text class="score">{{score}}</text><text class="hint">每日签到 +5 分，完成充电订单按实付金额取整奖励</text></view><view class="actions"><button class="action" :disabled="signing||signed" @click="sign">{{signed?'今日已签到':'每日签到 +5'}}</button><button class="action secondary" @click="load">刷新</button></view><view class="card"><view class="title">可领取订单奖励</view><view v-if="!orders.length" class="empty">暂无可领取的完成订单</view><view v-for="o in orders" :key="o.order_id" class="order"><view><text class="order-id">订单 {{o.order_number||o.order_id}}</text><text class="row-time">金额 ¥{{Number(o.ordergold||0).toFixed(2)}}</text></view><button class="claim" :disabled="claiming" @click="claim(o.order_id)">领取</button></view></view><view class="card"><view class="title">积分明细</view><view v-if="!ledger.length" class="empty">暂无积分流水</view><view v-for="row in ledger" :key="row.business_key" class="row"><view><text class="row-title">{{row.remark||'积分变动'}}</text><text class="row-time">{{row.create_time}}</text></view><text class="points">+{{row.points}}</text></view></view></view></template>
<script setup>
import {ref} from 'vue';import {onShow} from '@dcloudio/uni-app';import pageHeader from '../../components/page-header/index.vue';import request from '../../components/js/request.js'
const score=ref(0),signed=ref(false),signing=ref(false),claiming=ref(false),orders=ref([]),ledger=ref([])
function load(){request({url:'points/summary',success:r=>{if(r.data?.code===200)score.value=Number(r.data.data?.credit||0)}});request({url:'points/ledger',data:{page:1,pageSize:30},success:r=>{if(r.data?.code===200){ledger.value=r.data.data||[];signed.value=ledger.value.some(x=>x.type==='DAILY_SIGN')}}});request({url:'points/orders',success:r=>{if(r.data?.code===200)orders.value=r.data.data||[]}})}
function sign(){if(signing.value||signed.value)return;signing.value=true;request({url:'points/sign',method:'POST',success:r=>{if(r.data?.code===200){signed.value=true;uni.showToast({title:'签到成功 +5',icon:'success'});load()}else uni.showToast({title:r.data?.msg||'签到失败',icon:'none'})},complete:()=>signing.value=false})}
function claim(id){if(claiming.value)return;claiming.value=true;request({url:'points/orders/'+encodeURIComponent(id)+'/claim',method:'POST',success:r=>{if(r.data?.code===200){uni.showToast({title:'领取成功',icon:'success'});load()}else uni.showToast({title:r.data?.msg||'领取失败',icon:'none'})},complete:()=>claiming.value=false})}
onShow(()=>{if(uni.getStorageSync('token'))load()})
</script>
<style scoped>.page{min-height:100vh;background:#f3f7f5;padding-bottom:40rpx}.card{margin:22rpx 28rpx;background:#fff;border-radius:24rpx;padding:28rpx}.hero{background:linear-gradient(135deg,#5267a7,#758ac4);color:#fff}.label{display:block;font-size:25rpx;opacity:.85}.score{display:block;font-size:70rpx;font-weight:700;margin:14rpx 0}.hint{font-size:22rpx;opacity:.85}.actions{display:flex;gap:18rpx;margin:22rpx 28rpx}.action{flex:1;background:#008773;color:#fff;border-radius:14rpx;font-size:27rpx}.action::after,.claim::after{border:0}.action.secondary{background:#fff;color:#008773;border:1rpx solid #b9ddd0}.title{font-size:30rpx;font-weight:700}.order,.row{display:flex;justify-content:space-between;align-items:center;padding:22rpx 0;border-bottom:1rpx solid #edf2ef}.order:last-child,.row:last-child{border:0}.order-id,.row-title{display:block;font-size:26rpx}.row-time{display:block;color:#8a9b92;font-size:22rpx;margin-top:6rpx}.claim{background:#e1f4eb;color:#008773;font-size:24rpx;border-radius:12rpx;padding:8rpx 22rpx}.points{color:#008773;font-size:30rpx;font-weight:700}.empty{text-align:center;color:#9aaba2;padding:40rpx 0;font-size:24rpx}</style>
