# 基础镜像
FROM eclipse-temurin:8-jre-jammy
# author
MAINTAINER hcp

# 挂载目录
VOLUME /home/hcp
# 创建目录
RUN mkdir -p /home/hcp
# 指定路径
WORKDIR /home/hcp
# 复制jar文件到路径
COPY ./jar/hcp-auth.jar /home/hcp/hcp-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","hcp-auth.jar"]
