CREATE TABLE IF NOT EXISTS c_app_account (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  mobile VARCHAR(20) NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  member_id BIGINT NOT NULL UNIQUE,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
